# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotify' do
  inhibit_all_warnings!
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Alamofire', '~> 4.7'
  pod 'RealmSwift'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SVProgressHUD'
  # Pods for Spotify

  target 'SpotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
